apiVersion: v1
kind: Service
metadata: 
  labels: 
    service: keycloak-ambassador
  name: keycloak-ambassador
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind: Mapping
      name: keycloak_https_mapping
      prefix: /auth/
      rewrite: /auth/
      service: keycloak-http
      timeout_ms: 20000
spec:
  type: NodePort
  ports:
  - name: keycloak-ambassador
    port: 8443
    targetPort: 8443
  selector:
    service: keycloak-ambassador
