---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "maildev.fullname" . }}
  labels:
    app: {{ include "maildev.name" . }}
    chart: {{ include "maildev.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "maildev.name" . }}
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: maildev-smtp
  labels:
    app: {{ include "maildev.name" . }}
    chart: {{ include "maildev.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mail.port }}
      targetPort: {{ .Values.mail.port }}
      protocol: TCP
      name: smtp
  selector:
    app: {{ include "maildev.name" . }}
    release: {{ .Release.Name }}


