apiVersion: v1
kind: Service
metadata:
  name: hmda-remoting
  labels:
    app: hmda
spec:
  clusterIP: None
  selector:
    app: hmda
  ports:
    - protocol: TCP
      port: 2551
      targetPort: 2551
